'use client';
import localFont from "next/font/local";
import "./globals.css";
import { usePathname } from 'next/navigation';
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import AuthProvider from "./components/AuthProvider";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const path = pathname.toLowerCase();
  let isAuthPage = path.includes('/login') || path.includes('/register') || path.includes('/confirm');
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          { !isAuthPage && <Navbar />}
          {children}
          { !isAuthPage && <Footer />}
        </body>
      </html>
    </AuthProvider>
  );
}
